name: auto_easy_localization
description: A powerful Dart/Flutter tool for automated translation and localization management using Google Translate's free API. Supports smart translation mode, batch processing, and 70+ languages.
version: 1.0.0
homepage: https://github.com/ArdaKoksall/auto_easy_localization
repository: https://github.com/ArdaKoksall/auto_easy_localization
issue_tracker: https://github.com/ArdaKoksall/auto_easy_localization/issues
documentation: https://github.com/ArdaKoksall/auto_easy_localization#readme

topics:
  - localization
  - translation
  - i18n
  - flutter
  - dart

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  path: ^1.9.1
  yaml: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  
# Example configuration for auto_easy_localization
# auto_easy_localization:
#   source_locale: en
#   target_locales: [tr, es, fr, de]
#   translations_path: assets/translations
#   delay_between_requests: 100
#   max_retries: 3

